name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Run Tests
      run: ./gradlew test

    - name: Build Project
      run: ./gradlew assemble

    - name: Build Debug APK
      run: bash ./gradlew :app:assembleDebug

